FROM eclipse-temurin:11

LABEL mentainer="javaguides.net@gmail.com"

WORKDIR /app

COPY target/currency-exchange-0.0.1-SNAPSHOT.jar /app/eurrency-exchange.jar

ENTRYPOINT ["java", "-jar", "eurrency-exchange.jar"]